SHOW databases;

USE SCOTT;
SELECT *
FROM EMP;

# WAQTD DETAILS OF EMPLOYEES IF THEIR ANNUAL SALARY IS MORE THAN 9000 AND DISPLAY THEIR SALARY
SELECT * , SAL*6 AS HALF_TERM
FROM EMP
WHERE SAL*12 > 9000;

# WAQTD NAME AND JOB AN D SALARY OF THE EMPLOYEEES WHO IS WORKING AS CLERK
SELECT ENAME, JOB , SAL
FROM EMP
WHERE JOB = 'CLERK';

# WAQTD DETAILS OF EMPLOYEES WORKING AS ANALYST AND THEIR SALARY SHOULD BE LESS THAN 5000
SELECT *
FROM EMP
WHERE JOB = 'ANALYST' AND SAL<5000;

# WAQTD DETAILS OF EMPLOYES ALONG WITH HALF_TERM_SALARY IF THEY ARE HIRED IN OR AFTER 1980
# AND EARN MORE THAN 2000 AND WORKING AS MANAGER
SELECT *, SAL*6 AS HALF_TERM_SALARY
FROM EMP
WHERE HIREDATE > '1979-12-31' AND SAL>2000 AND JOB = 'MANAGER';

# WAQTD DETAILS OF EMPLOYEES HIREDATE IN THE YEAR OF 1980 AND THEIR HALF_TERM IS LESS THAN 7000

SELECT *, SAL*6 AS HALF_TERM_SALARY
FROM EMP
WHERE HIREDATE >='1980-1-1' AND HIREDATE < '1981-1-1' AND SAL*6 < 7000;

# WAQTD ALL DETAIL OF EMP WORKING AS SALESMAN OR CLERK OR ANALYST
SELECT *
FROM EMP
WHERE JOB = 'ANALYST' OR JOB = 'CLERK' OR JOB = 'SALESMAN';

# WAQTD ALL DETAIL OF EMP WORKING AS SALESMAN, OR ANALYST AND EARN MORE THAN 2000;
SELECT *
FROM EMP
WHERE (JOB = 'ANALYST' OR JOB = 'SALESMAN') AND SAL>2000;

# WAQTD ALL DETAIL OF EMP WORKING AS SALESMAN, OR MANAGER ERNAING MORE THAN 2000 AND
# LESS THAN 5000 AND HIRE AFTER 1982 AND BEFORE 1987.
SELECT *
FROM EMP
WHERE (JOB = 'MANAGER' OR JOB = 'SALESMAN') AND SAL>2000 AND SAL<5000 AND
 HIREDATE > '1982-12-31' AND HIREDATE< '1987-1-1';
 
 #WAQTD DETAILS OF EMP EARN MORE THAN 2000 BUT JOB SHOULD NOT BE MANAGER
 SELECT *
 FROM EMP
 WHERE SAL>2000 AND NOT JOB = 'MANAGER';
 # WAQTD DETAILS OF EMP IF THEY ARE NOT WORKING AS MANAGER OR SALESMAN BUT THEY ARE EARNING ANUAL SALARY LESS THAN 15000;
 SELECT *
 FROM EMP
 WHERE NOT(JOB = 'MANAGER' OR JOB = 'SALESMAN') AND SAL*12 < 15000;
 
 # WAQTD DETAILS OF EMPLOUEE WORKING as analystor clerk or salesmen heired after 1980 in deparment number 10,30
 select *
 from emp
 where job in('ANALYST','CLERK','SALESMAN') and hiredate >= '1980-1-1' 
 and deptno in(10,30);
 
 #WAQTD NAME JOB AND HIREDATE OF EMPLOYEE WHO IS HIRE BEFORE 1987 WORKING AS CLERK OR
 #MANAGER BUT NOT WORKING IN DEPARTMENT NUMBER 20,30
 SELECT ENAME, JOB, HIREDATE
 FROM EMP
 WHERE HIREDATE < '1987-1-1' AND JOB IN('CLERK','MANAGER') AND DEPTNO NOT IN(20,30);
 
 #WAQTD DETAILS OF EMP ALONG WITH HALF TERM SALARY IF THEY ARE ERNING IN THE RANGE OF
 # 1000 TO 5000 BUT THEY ARE NOT WORKING AS SALESMAN OR ANALYST
 SELECT *, SAL*6 AS HALF_TERM_SALARY
 FROM EMP
 WHERE (SAL BETWEEN '1000' AND 5000) AND JOB NOT IN('SALESMAN', 'ANALYST');
 
 # WAQTD DETAILS OF EMP IF THEY ARE HAVING SALARY MORE THAN 2000 AND LESS THEN 6000
 #AND THEY ARE HEIRED AFTER 1978 AND BEFORE 1986
SELECT *
FROM EMP
WHERE (SAL BETWEEN '2000' AND 6000) AND (HIREDATE BETWEEN '1980-1-1' AND '1985-12-31');

SHOW tables;
SELECT * FROM DEPT;

#WAQTDFOE WHO ARE WORKING IN THE LOCATION L2
SELECT *
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'NEW YORK');

#WAQTD NUMBER OF EMPLOYEE WORKING AS CLERK IN THE SAME DEPTNO AS SMITH AND EARNING MORE
#THAN KING , HIRED AFTER MARTIN IN LOC BOSTON

SELECT *
FROM EMP
WHERE JOB = 'CLERK'
AND DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'SMITH')
AND SAL > (SELECT SAL FROM EMP WHERE ENAME = 'KING')
AND HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME = 'MARTIN')
AND DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'BOSTON');

#WAQTD DEPARMENT NAME OF CLERK 

SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE JOB = 'CLERK');

#WAQTDDOE WHO IS ERNING MAXIMUM SALARY
SELECT *
FROM EMP
WHERE SAL = (select MAX(SAL) FROM EMP);

#WAQTD DISPLAY DETAILS OF EMP WITH 2ND LARGEST SALARY
SELECT * FROM EMP
WHERE SAL = (SELECT MAX(SAL) FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP));

#WAQTD LOC OF EMP WHO IS EARNING 3RD MAX SAL
SELECT LOC FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP 
	WHERE SAL IN (SELECT MAX(SAL) FROM EMP
		WHERE SAL < (SELECT MAX(SAL) FROM EMP
			WHERE SAL < (SELECT MAX(SAL) FROM EMP))));
            
#WAQTD NAME AND HIRE DATE OF THE EMP WHO IS EARNING MORE THAN CLERK
SELECT ENAME , HIREDATE
FROM EMP
WHERE SAL>(SELECT MAX(SAL) FROM EMP WHERE JOB = 'CLERK');

SELECT ENAME, HIREDATE
FROM EMP
WHERE SAL >ALL(SELECT SAL FROM EMP WHERE JOB='CLERK');

#WAQTD DOE EARNING LESS THAN SALESMAN AND HIREDATE AFTER ALL THE CLERK
SELECT * FROM EMP
WHERE SAL<ALL(SELECT SAL FROM EMP WHERE JOB= 'SALESMAN') 
AND HIREDATE>ALL(SELECT HIREDATE FROM EMP WHERE JOB='CLERK');

#WAQTD DOE EARNING MORE THAN EMPLOYEES WHAVING CHARACTER A IN HIS NAME 
#AND EARNING LESS THAN THE EMP WHO IS WORKING IN THE LOC OF CHICAGO
select * FROM EMP
WHERE SAL>ALL(SELECT SAL FROM EMP WHERE ENAME LIKE"%A%")
AND SAL<ALL(SELECT SAL FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT 
	WHERE LOC = 'CHICAGO'));
    
#WAQTD DOE EARNING MORE THAN ATLEAST A CHERK
SELECT * FROM EMP
WHERE SAL>ANY(SELECT SAL FROM EMP WHERE JOB = 'CLERK');

#WAQTD NAME AND HIREDATE AND ANUALSAL OF THE EMP IF THIS ANUAL SAL IS GREATER THAN 
#ANY ONE OF CLERK'S ANUAL SAL BUT THOSE EMPLOOYEES ARE HIRED AFTER MANAGERS
sELECT ENAME, HIREDATE, SAL*12 AS ANUAL_SAL
FROM EMP
WHERE SAL*12 > ANY(sELECT SAL*12 FROM EMP WHERE JOB = 'CLERK') 
AND HIREDATE > ALL(SELECT HIREDATE FROM EMP WHERE JOB = 'MANAGER');
    
# WAQTD NAMES AND HALFTEM SAL OF EMP WHO IS HIRED AFTER ADAM AND EARNING LESS THAN
# EMP WHO IS HAVING CHARACTER MAN IN HIS JOB TITLE AND THEY ARE HIRED AFTER ATLEAST
# ONE SALESMAN AND THEIR SALARY IS IN RANGE 1000 TO 5000
SELECT ENAME, SAL*6 AS HALFTERM_SAL
FROM EMP
WHERE HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME = 'ADAM')
AND SAL<(SELECT SAL FROM EMP WHERE JOB LIKE "%MAN%")
AND HIREDATE>ANY(SELECT HIREDATE FROM EMP WHERE JOB='SALESMAN')
AND SAL BETWEEN 999 AND 5001;

#CROSS JOIN
SELECT *
FROM EMP CROSS JOIN DEPT;

SHOW TABLES;

#INNER JOIN
SELECT *
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

#WAQTD DETAILS OF EMP AND THEIR DEPT IF THE EMPYOYEE ARE EARNING MORE THAN 3000
SELECT *
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SAL>3000;

#WAQTD DEPT ALONG WITH EMP NAME IF WMP ARE WORKING IN THE LOCATION OF CHICAGO
# AND THE ARE HIRED AFTER CLERK
SELECT DEPT.* , ENAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE LOC = 'CHICAGO' AND HIREDATE = ALL(SELECT HIREDATE FROM EMP WHERE JOB='CLERK');

#WAQTD NUMBER NOT EMP WORKING IN EACH DEPT IF THEIR MOX SAL IS MORE THA 2000 
#AND THEIR LOC IS NEWYOURK OR CHICAGO AND THEY ATE HEIRED AFTER THE EMPLOYEE 
#WHO IS NOT EARNING COMMITION
SELECT COUNT(*),EMP.DEPTNO
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO=DEPT.DEPTNO
WHERE LOC = ('NEW YORK' OR 'CHICAGO') 
	AND HIREDATE>ALL(SELECT HIREDATE FROM EMP WHERE (COMM IS NULL OR COMM = 0.00))
GROUP BY EMP.DEPTNO
HAVING MAX(SAL)>2000;

#QUERY TO DISPLAY DEDAILS OF FORDS MANAGER
SELECT *
FROM EMP
WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME='FORD');

#DISPLAY NAME AND HIREDATRE OF ADAMS MANAGER
select ENAME, HIREDATE
FROM EMP
WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME = 'ADAMS');

#DISPLAY NAME AND HIREDATRE OF SMITH'S MANAGER'S MANAGER DETAILS
select ENAME, HIREDATE
FROM EMP
WHERE EMPNO = (SELECT MGR FROM EMP WHERE EMPNO = 
	(SELECT MGR FROM EMP WHERE ENAME = 'ADAMS'));
    
# DETAILS OM EMP REPORTHINF TO KING
SELECT *
FROM EMP 
WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'KING');

#DETAIS OF EMP AND THEIR MANAGER DETAILS
#self join
SELECT *
FROM EMP AS E1 JOIN EMP AS E2
ON E1.MGR = E2.EMPNO;

#NSMRD OG RMP AND THEIR MANAGERS IF EMP ARE EARNING MORE THAN 2000
SELECT *
FROM EMP AS E1 JOIN EMP AS E2
ON E1.MGR = E2.EMPNO
WHERE E1.SAL > 2000;

#NAMES OF EMP AND THEIR MANAGER IF EMP ARE EARNING MORE THAN THEIR MANAGERS AND MANAGERS ARE HEIRED AFTER CLERK
SELECT EMPT.ENAME AS EMPLOYEE, MGRT.ENAME AS MANAGER
FROM EMP AS EMPT JOIN EMP AS MGRT
ON EMPT.MGR = MGRT.EMPNO
WHERE EMPT.SAL > MGRT.SAL AND MGRT.HIREDATE >ALL(select HIREDATE FROM EMP WHERE JOB = 'CLERK');

#DETAILS OF EMP AND THEIR MANAGER AND THEIR MANAGER

SELECT *
FROM EMP AS E1 JOIN EMP AS E2
ON E1.MGR = E2.EMPNO
JOIN EMP AS E3
ON E2.MGR = E3.EMPNO;

#DETAILS OF EMP AND THEIR MANAGER AND THEIR MANAGER IF EMPLOYEE ARE ERNING MORETHAN their manage 
#and manager are hired after blake and manager's manager are working indept 10 or 30
SELECT *
FROM EMP E1 JOIN EMP E2
ON E1.MGR = E2.EMPNO
JOIN EMP E3
ON E2.MGR = E3.EMPNO
WHERE E1.SAL>E2.SAL AND E2.HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME = 'BLAKE') 
	AND E3.DEPTNO IN (10,30) 
	AND (E1.ENAME LIKE "%A%" OR E1.ENAME LIKE "%S%")
    AND (E2.ENAME LIKE "%A%" OR E2.ENAME LIKE "%S%")
    AND (E3.ENAME LIKE "%A%" OR E3.ENAME LIKE "%S%");
    
#NSMES OF EMP AND THEIR MANAGER AND THEIR MANAGER ALONG WITH THEIR DEPARTMENT NAME
SELECT 
    E1.ENAME AS Employee, 
    D1.DNAME AS Emp_Dept,
    E2.ENAME AS Manager, 
    D2.DNAME AS Mgr_Dept,
    E3.ENAME AS Grand_Manager, 
    D3.DNAME AS Grand_Mgr_Dept
FROM EMP E1
-- Join to get the Manager
JOIN EMP E2 ON E1.MGR = E2.EMPNO
-- Join to get the Manager's Manager (Grand-Manager)
JOIN EMP E3 ON E2.MGR = E3.EMPNO
-- Join for Employee's Department
JOIN DEPT D1 ON E1.DEPTNO = D1.DEPTNO
-- Join for Manager's Department
JOIN DEPT D2 ON E2.DEPTNO = D2.DEPTNO
-- Join for Grand-Manager's Department
JOIN DEPT D3 ON E3.DEPTNO = D3.DEPTNO;

#NATURAL JOIN
SELECT *
FROM EMP
NATURAL JOIN DEPT;

#LEFT OUTER JOIN
SELECT 
    E.ENAME AS Employee, 
    M.ENAME AS Manager
FROM EMP E
LEFT OUTER JOIN EMP M ON E.MGR = M.EMPNO;

#FULL OUTER JOIN
SELECT * FROM EMP LEFT JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO
UNION
SELECT * FROM EMP RIGHT JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO;

#co related sub query
#disply 5th minimum salary 
select e1.sal
from emp e1
where 5-1 in (select count(distinct e2.sal)
	from emp e2
    where e1.sal>e2.sal);
    
#query to disply emloyee who is earning 7th max sal
select *
from emp e1
where 7-1 in (select count(distinct e2.sal)
	from emp e2
    where e1.sal<e2.sal);
    
# 4th and 5th max sal
select *
from emp e1
where 7-1 in (select count(distinct e2.sal)
	from emp e2
    where e1.sal<e2.sal)
    or
    5-1 in (select count(distinct e2.sal)
	from emp e2
    where e1.sal<e2.sal);
    
select *
from emp e1
where (select count(distinct e2.sal)
	from emp e2
    where e1.sal<e2.sal) in (7-1,5-1);
    
# first 5 max
select e1.sal
from emp e1
where (select count(distinct e2.sal)
	from emp e2
    where e1.sal<e2.sal)<=5-1;
    
#2nd max sal of each dept

#details of employees whoes salary is greater than avg sal of their own dept
select *
from emp
where sal > any(select avg(sal) from emp group by deptno);

select substring(job,1,3)
from emp;

select length('yashraj') - length(replace('yashraj','a',''));

select *
from emp
where 2 = (length(ename) - length(replace(ename,'L','')));

select *
from emp
where 